version: '3.9'
services:
    apache:
      image: lcubestudios/apache2
      container_name: ${APP_CONTAINER_NAME}
      build:
        context: apache2
      volumes:
        - ./apache2:/var/www/html
      ports:
        - "${APP_PORT}:80"

    postgres:
      image: lcubestudios/postgres
      container_name: ${PS_DB_CONTAINER_NAME}
      build:
        context: postgres
      ports:
        - "${PS_DB_PORT}:5432"
      restart: always
      environment:
        - POSTGRES_USER=${PS_DB_USER}
        - POSTGRES_PASSWORD=${PS_DB_PASSWORD}
      volumes:
        - ./postgres/pgdata:/var/lib/postgresql/data
    
    phppgadmin:
      container_name: ${PGA_CONTAINER_NAME}
      image: bitnami/phppgadmin
      environment:
        - DATABASE_HOST=postgres
      ports: 
        - "${PGA_HTTP_PORT}:8080"
      depends_on:
        - postgres
    
    # mysql:
    #   image: mysql
    #   container_name: ${MS_DB_CONTAINER_NAME}
    #   restart: always
    #   environment:
    #     MYSQL_USER: ${MS_DB_USER}
    #     MYSQL_PASSWORD: ${MS_DB_PASSWORD}
    #     MYSQL_DATABASE: ${MS_DB_NAME}
    #   ports:
    #     - "${MS_DB_PORT}:3306"
    #   volumes:
    #     - ./mysql/:/var/lib/mysql

    # phpmyadmin:
    #   image: phpmyadmin
    #   container_name: ${PMA_CONTAINER_NAME}
    #   restart: always
    #   ports:
    #     - ${PMA_HTTP_PORT}:80
    #   depends_on:
    #     - mysql
